# Generated by Django 4.2.6 on 2023-10-11 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('COMPLETED', 'Completed'), ('DEVELOPING', 'Developing'), ('STAND_BY', 'stand by'), ('DISCARDED', 'Discarted')], default='STAND_BY', max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('dead_line', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project_Users', to='signup.users')),
                ('in_work_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project_WorkSpaces', to='signup.workspaces')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('COMPLETED', 'Completed'), ('DEVELOPING', 'Developing'), ('STAND_BY', 'stand by'), ('DISCARDED', 'Discarted')], default='STAND_BY', max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('dead_line', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('belongs_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tasks_Project', to='projects_tasks_and_activities.project')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tasks_Users', to='signup.users')),
                ('in_work_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tasks_WorkSpaces', to='signup.workspaces')),
            ],
        ),
        migrations.CreateModel(
            name='CommentsTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=250)),
                ('belongs_Tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentsTasks_Project', to='projects_tasks_and_activities.tasks')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentsTasks_Users', to='signup.users')),
                ('in_work_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentsTasks_WorkSpaces', to='signup.workspaces')),
            ],
        ),
        migrations.CreateModel(
            name='CommentsProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=250)),
                ('belongs_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentsProject_Project', to='projects_tasks_and_activities.project')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentsProject_Users', to='signup.users')),
                ('in_work_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentsProject_WorkSpaces', to='signup.workspaces')),
            ],
        ),
        migrations.CreateModel(
            name='CommentsActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=250)),
                ('belongs_activitie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentsActivities_Project', to='projects_tasks_and_activities.project')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentsActivities_Users', to='signup.users')),
                ('in_work_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentsActivities_WorkSpaces', to='signup.workspaces')),
            ],
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('COMPLETED', 'Completed'), ('DEVELOPING', 'Developing'), ('STAND_BY', 'stand by'), ('DISCARDED', 'Discarted')], default='STAND_BY', max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('dead_line', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('belongs_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Activities_Task', to='projects_tasks_and_activities.tasks')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Activities_Users', to='signup.users')),
                ('in_work_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Activities_WorkSpaces', to='signup.workspaces')),
            ],
        ),
    ]
