# Generated by Django 4.2.6 on 2023-10-12 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('COMPLETED', 'Completed'), ('DEVELOPING', 'Developing'), ('STAND_BY', 'stand by'), ('DISCARDED', 'Discarted')], default='STAND_BY', max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('dead_line', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommentsActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CommentsProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CommentsTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('COMPLETED', 'Completed'), ('DEVELOPING', 'Developing'), ('STAND_BY', 'stand by'), ('DISCARDED', 'Discarted')], default='STAND_BY', max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('dead_line', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('COMPLETED', 'Completed'), ('DEVELOPING', 'Developing'), ('STAND_BY', 'stand by'), ('DISCARDED', 'Discarted')], default='STAND_BY', max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('dead_line', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('belongs_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tasks_Project', to='projects_tasks_and_activities.project')),
            ],
        ),
    ]
