# Generated by Django 4.2.6 on 2023-10-12 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_work_space_manager', '0001_initial'),
        ('projects_tasks_and_activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tasks_Users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasks',
            name='in_work_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tasks_WorkSpaces', to='user_work_space_manager.workspaces'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project_Users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='in_work_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project_WorkSpaces', to='user_work_space_manager.workspaces'),
        ),
        migrations.AddField(
            model_name='commentstasks',
            name='belongs_Tasks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentsTasks_Project', to='projects_tasks_and_activities.tasks'),
        ),
        migrations.AddField(
            model_name='commentstasks',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentsTasks_Users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentstasks',
            name='in_work_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentsTasks_WorkSpaces', to='user_work_space_manager.workspaces'),
        ),
        migrations.AddField(
            model_name='commentsproject',
            name='belongs_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentsProject_Project', to='projects_tasks_and_activities.project'),
        ),
        migrations.AddField(
            model_name='commentsproject',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentsProject_Users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentsproject',
            name='in_work_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentsProject_WorkSpaces', to='user_work_space_manager.workspaces'),
        ),
        migrations.AddField(
            model_name='commentsactivities',
            name='belongs_activitie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentsActivities_Project', to='projects_tasks_and_activities.project'),
        ),
        migrations.AddField(
            model_name='commentsactivities',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentsActivities_Users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentsactivities',
            name='in_work_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentsActivities_WorkSpaces', to='user_work_space_manager.workspaces'),
        ),
        migrations.AddField(
            model_name='activities',
            name='belongs_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Activities_Task', to='projects_tasks_and_activities.tasks'),
        ),
        migrations.AddField(
            model_name='activities',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Activities_Users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activities',
            name='in_work_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Activities_WorkSpaces', to='user_work_space_manager.workspaces'),
        ),
    ]
