# Generated by Django 4.2.6 on 2023-10-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_tasks_and_activities', '0003_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='description',
            field=models.CharField(default='Empty', max_length=250),
            preserve_default=False,
        ),
    ]
