# Generated by Django 4.2.6 on 2023-10-18 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_work_space_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolassignment',
            name='rol',
            field=models.CharField(choices=[('CREATOR_WORK_SPACE', 'creator'), ('AREA_LEAD', 'area lead'), ('COLLABORATOR', 'collaborator')], max_length=20),
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_lead_collaborator', to=settings.AUTH_USER_MODEL)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator_area_lead', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
