# Generated by Django 4.2.6 on 2023-10-18 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_work_space_manager', '0002_alter_rolassignment_rol_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='work_space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_work_space_manager.workspaces'),
            preserve_default=False,
        ),
    ]
