# Generated by Django 4.2.6 on 2023-10-18 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_work_space_manager', '0003_teams_work_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='area_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_lead_collaborator', to=settings.AUTH_USER_MODEL),
        ),
    ]
