# Generated by Django 4.2.6 on 2023-10-18 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_work_space_manager', '0004_alter_teams_area_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collaborator_area_lead', to=settings.AUTH_USER_MODEL),
        ),
    ]
